db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=jdbc:sqlserver://localhost:1433;databaseName=OpsPulseDB;encrypt=true;trustServerCertificate=true
db.username=sa
db.password=YourStrong!Pass123
db.entity.package=org.example.model